name: bio-tutorial
channels:
  - biocore
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bleach=1.4.2=py36_0
  - libffi=3.2.1=1
  - nglview=1.1.6=py_0
  - mafft=7.245=0
  - biopython=1.72=py36_0
  - ca-certificates=2018.8.13=ha4d7672_0
  - cycler=0.10.0=py_1
  - ipywidgets=7.4.0=py_0
  - kiwisolver=1.0.1=py36h2d50403_2
  - matplotlib=2.2.3=py36h0e0179f_0
  - mkl_fft=1.0.5=py36_0
  - mkl_random=1.0.1=py36_0
  - olefile=0.45.1=py_1
  - openssl=1.0.2o=h470a237_1
  - pip=18.0=py36_1
  - pyparsing=2.2.0=py_1
  - python-dateutil=2.7.3=py_0
  - pytz=2018.5=py_0
  - reportlab=3.5.5=py36h77bcf2c_0
  - setuptools=40.0.0=py36_1
  - tornado=5.1=py36h470a237_1
  - wheel=0.31.1=py36_1
  - appnope=0.1.0=py36hf537a9a_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - certifi=2018.8.13=py36_0
  - dbus=1.13.2=h760590f_1
  - decorator=4.3.0=py36_0
  - entrypoints=0.2.3=py36_2
  - expat=2.2.5=hb8e80ba_0
  - freetype=2.9.1=hb4e5f40_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.56.1=h35bc53a_0
  - html5lib=1.0.1=py36_0
  - icu=58.2=h4b95b61_1
  - intel-openmp=2018.0.3=0
  - ipykernel=4.8.2=py36_0
  - ipython=6.5.0=py36_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - jedi=0.12.1=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=he5867d9_2
  - jsonschema=2.6.0=py36hb385e00_0
  - jupyter=1.0.0=py36_4
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36_1
  - jupyter_core=4.4.0=py36_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1.20170329=hb402a30_2
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.34=he12f830_0
  - libsodium=1.0.16=h3efe00b_0
  - libtiff=4.0.9=hcb84e12_1
  - markupsafe=1.0=py36h1de35cc_1
  - mistune=0.8.3=py36h1de35cc_1
  - mkl=2018.0.3=1
  - nbconvert=5.3.1=py36_0
  - nbformat=4.4.0=py36h827af21_0
  - ncurses=6.1=h0a44026_0
  - notebook=5.5.0=py36_0
  - numpy=1.15.0=py36h648b28d_0
  - numpy-base=1.15.0=py36h8a80b8c_0
  - pandoc=2.2.1=h1a437c5_0
  - pandocfilters=1.4.2=py36_1
  - parso=0.3.1=py36_0
  - pcre=8.42=h378b8a2_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36hf512f8e_0
  - pillow=5.2.0=py36hb68e598_0
  - prompt_toolkit=1.0.15=py36haeda067_0
  - ptyprocess=0.6.0=py36_0
  - pygments=2.2.0=py36h240cd3f_0
  - pyqt=5.9.2=py36h655552a_0
  - python=3.6.6=hc167b69_0
  - pyzmq=17.1.2=py36h1de35cc_0
  - qt=5.9.6=h74ce4d9_0
  - qtconsole=4.4.0=py36_0
  - readline=7.0=hc1231fa_4
  - send2trash=1.5.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.8=py36h0a44026_0
  - six=1.11.0=py36_1
  - sqlite=3.24.0=ha441bb4_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36h625a49b_0
  - tk=8.6.7=h35a86e2_3
  - traitlets=4.3.2=py36h65bd3ce_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - webencodings=0.5.1=py36_1
  - widgetsnbextension=3.4.0=py36_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.2.5=h0a44026_0
  - zlib=1.2.11=hf3cbc9b_2
prefix: /usr/local/miniconda3/envs/bio-tutorial

